### ISSUE TITLE
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM

### ISSUE THREAD

**Issue by srebrny** [pavlepredic/Yii-sitemap-module#2]
Hi, 

When i publish my site on production server i see this error: 

``` php
Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home/...../protected/extensions/sitemap/SitemapModule.php on line 222
```

line 222 

``` php
foreach ($class::model()->findAll($criteria) as $model)
```

This bug exists in php > 5.3

To fix this issue change line 222 to:

``` php
foreach ($class->model()->findAll($criteria) as $model)
```

**Comment by pavlepredic** [comment]
See here: http://php.net/manual/en/language.oop5.paamayim-nekudotayim.php
"As of PHP 5.3.0, it's possible to reference the class using a variable."
Also see example on same page:
$classname = 'MyClass';
echo $classname::CONST_VALUE; // As of PHP 5.3.0

Make sure you really are using 5.3.0 or higher. I just tested with 5.3.8 and it works. In 5.2.17 it results in a parse error.

Your proposed solution would not work because $class variable holds a string and not an object. Don't forget that this module caches data by default, so clear cache (or disable it) when making changes to code. Maybe you can try doing this (if all else fails):

``` php
foreach (CActiveRecord::model($class)->findAll($criteria) as $model)
```

Or upgrade your PHP...

**Comment by srebrny** [comment]
Ok, I update the php and works fine, thanks.
